name: Run Curl on Push

on:
  push:
    branches:
      - main
      - feature/*  # Replace with your branch pattern

jobs:
  curl:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref }}
      COMMIT_AUTHOR: ${{ github.actor }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Curl
      run: |
        curl -d "New push on $BRANCH_NAME by $COMMIT_AUTHOR
        $COMMIT_MESSAGE" http://ntfy.sh/cub3d
